# how to use tmux:
# c-a d: close tmux
# c-a %: split vertical
# c-a ": split horizontal
# c-a c: new window
# c-a z: maximize pane
# c-a x: close window/splitted window
# c-a n: move to next window
# c-a p: move to previous window
# c-a ,: rename tab
# c-a hjkl: focus windows
# c-shift arrows: to move windows
# c-a:resize-pane -<U/D/L/R> <number>: ex c-a:resize-pane -D 20 to resize down the pane of 20
# to kill tmux
# c-a :kill-session
#
# to refresh tmux config
# tmux source-file ~/.tmux.conf
#
# copy/paste text
#
# enter copy mode
# ctrl + b + [ 
# select text using view mode (v) and press enter to copy it
# ctrl + b + ] to paste
# 
# if I have "set -g mouse on" I can just select the text with the mouse to copy it, and paste it as above
#
# to copy text from tmux to system clipboard
#
# sudo apt update && sudo apt install xclip
# the command below copies the selected text in the system clipboard using the "y" key
# bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
#
# to paste text from system clipboard to tmux
# ctrl + shift + v

# set zsh as default shell
set-option -g default-shell /bin/zsh

set -g status-style 'bg=#333333 fg=#5eacd3'
set-option -g default-terminal "screen-256color"

# enable scroll using mouse/touchbar
set -g mouse on

# custom prefix
set-option -g prefix C-a

bind -r k select-pane -U 
bind -r j select-pane -D 
bind -r h select-pane -L 
bind -r l select-pane -R

# Easy config reload
bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded."

# Moving window
bind-key -n C-S-Left swap-window -t -1 \; previous-window
bind-key -n C-S-Right swap-window -t +1 \; next-window

#### basic settings
set-option -g status-justify "left"
set-window-option -g mode-keys vi

# copy selected text to system clipboard using "y"
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
