
# how to use tmux:
# c-b d: close tmux
# c-b %: split vertical
# c-b ": split horizontal
# c-b c: new window
# c-b z: maximize pane
# c-b x: close window/splitted window
# c-b n: move to next window
# c-b p: move to previous window
# c-b ,: rename tab
# c-b hjkl: focus windows
# c-shift arrows: to move windows
# c-b:resize-pane -<U/D/L/R> <number>: ex c-a:resize-pane -D 20 to resize down the pane of 20

# to kill tmux
# c-b :kill-session

# to refresh tmux config
# tmux source-file ~/.tmux.conf

# set zsh as default shell if exists, otherwise set bash
if-shell "[ -x /bin/zsh ]" \
  "set-option -g default-shell /bin/zsh" \
  "set-option -g default-shell /bin/bash"

# use default shell
# set-option -g default-shell /bin/zsh
# set-option -g default-shell /bin/bash

set-option -g default-terminal "screen-256color"
# enable scroll using mouse/touchbar
set -g mouse on

# custom prefix
# set-option -g prefix C-a

bind -r k select-pane -U 
bind -r j select-pane -D 
bind -r h select-pane -L 
bind -r l select-pane -R

# Easy config reload
bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded."

# Moving window
bind-key -n C-S-Left swap-window -t -1 \; previous-window
bind-key -n C-S-Right swap-window -t +1 \; next-window

#### basic settings
set-option -g status-justify "left"
set-window-option -g mode-keys vi
