# put this on your ~/.bashrc file to autostart tmux
# if command -v tmux &> /dev/null && [ -n "$PS1" ] && [[ ! "$TERM" =~ screen ]] && [[ ! "$TERM" =~ tmux ]] && [ -z "$TMUX" ]; then
#  exec tmux
# fi

# how to use tmux:
# c-a d: close tmux
# c-a %: split vertical
# c-a ": split horizontal
# c-a c: new window
# c-a z: maximize pane
# c-a x: close window/splitted window
# c-a n: move to next window
# c-a p: move to previous window
# c-a ,: rename tab
# c-a hjkl: focus windows
# c-shift arrows: to move windows
# c-b:resize-pane -<U/D/L/R> <number>: ex c-a:resize-pane -D 20 to resize down the pane of 20

# to kill tmux
# c-a :kill-session

# to refresh tmux config
# tmux source-file ~/.tmux.conf

# Prime theme
set -g status-style 'bg=#333333 fg=#5eacd3'

# OneDark dark theme
# set -g status-style 'bg=#31353f fg=#55b1bd'

# Custom color
#set -g status-style 'bg=#98c379 fg=#282c34'

# Fix TMUX colors for Neovim
# set -g default-terminal "tmux-256color"
# set -ga terminal-overrides ",*256col*:Tc"
# set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q'
# set-environment -g COLORTERM "truecolor"

set-option -g default-shell /usr/bin/zsh

set-option -g default-terminal "screen-256color"
# enable scroll using mouse/touchbar
# set -g mouse on

# custom prefix
set-option -g prefix C-a

bind-key -r k select-pane -U
bind-key -r j select-pane -D
bind-key -r h select-pane -L
bind-key -r l select-pane -R

# Easy config reload
bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded."

# Moving window
bind-key -n C-S-Left swap-window -t -1 \; previous-window
bind-key -n C-S-Right swap-window -t +1 \; next-window

#### basic settings
# set-option -g status-justify "left"
set-window-option -g mode-keys vi

### Fix Neovim delay when pressing ESC
set-option -sg escape-time 10
